DROP DATABASE IF EXISTS COMPANY;
CREATE DATABASE COMPANY;
USE COMPANY;

CREATE TABLE EMPLOYEES (
EMPLOYEE_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(30) NOT NULL,
LAST_NAME VARCHAR(30) NOT NULL,
SALARY DECIMAL(10,2) NOT NULL,
DEPARTMENT_ID VARCHAR(10)
);

-- Q1
CREATE TABLE EMPID_SEQ (
    SEQ_NAME VARCHAR(20) PRIMARY KEY,
    CURR_VALUE INT NOT NULL
);
INSERT INTO EMPID_SEQ VALUES ('EMPID_SEQ',100);

-- Q2
SELECT CURR_VALUE AS CURRENT_VALUE FROM EMPID_SEQ;
UPDATE EMPID_SEQ SET CURR_VALUE=CURR_VALUE+1 WHERE SEQ_NAME='EMPID_SEQ';

-- Q3
ALTER TABLE EMPID_SEQ
ADD CONSTRAINT CHECK_MAX CHECK (CURR_VALUE<=1000);
SELECT * FROM EMPID_SEQ;

-- Q4:
INSERT INTO EMPLOYEES
SELECT CURR_VALUE,'ANMOL','THAPLIYAL',40000,'10' FROM EMPID_SEQ;

UPDATE EMPID_SEQ SET CURR_VALUE=CURR_VALUE+1 WHERE SEQ_NAME='EMPID_SEQ';
INSERT INTO EMPLOYEES
SELECT CURR_VALUE,'RAHUL','MANKANI',35000,'20' FROM EMPID_SEQ;

UPDATE EMPID_SEQ SET CURR_VALUE=CURR_VALUE+1 WHERE SEQ_NAME='EMPID_SEQ';
INSERT INTO EMPLOYEES
SELECT CURR_VALUE,'KAPIL','NEGI',45000,'30' FROM EMPID_SEQ;

SELECT * FROM EMPLOYEES;

-- Q5
DROP TABLE EMPID_SEQ;

-- Q6
CREATE TABLE REVERSE_SEQ (
    SEQ_NAME VARCHAR(20) PRIMARY KEY,
    CURR_VALUE INT NOT NULL,
    MIN_VALUE INT,
    STEP_VALUE INT
);

INSERT INTO REVERSE_SEQ VALUES ('REVERSE',10000,1000,-5);

CREATE TABLE REVERSE_LOG (
    VALUE INT
);

DELIMITER //
CREATE PROCEDURE GENRATE()
BEGIN
    DELETE FROM REVERSE_LOG;

    WHILE (SELECT CURR_VALUE FROM REVERSE_SEQ) > (SELECT MIN_VALUE FROM REVERSE_SEQ) DO
        INSERT INTO REVERSE_LOG(VALUE)
        SELECT CURR_VALUE FROM REVERSE_SEQ;

        UPDATE REVERSE_SEQ
        SET CURR_VALUE = CURR_VALUE + STEP_VALUE
        WHERE SEQ_NAME='REVERSE';
    END WHILE;

    INSERT INTO REVERSE_LOG(VALUE)
    SELECT CURR_VALUE FROM REVERSE_SEQ;
END //
DELIMITER ;

CALL GENRATE();

SELECT * FROM REVERSE_LOG;