DROP DATABASE IF EXISTS COMPANY;
CREATE DATABASE COMPANY;
USE COMPANY;

CREATE TABLE DEPARTMENT (
    DNAME VARCHAR(30) NOT NULL,
    DNUM INT PRIMARY KEY,
    MGR_SSN VARCHAR(10),
    MGR_START_DATE DATE
);

CREATE TABLE EMPLOYEE (
    FNAME VARCHAR(30) NOT NULL,
    LNAME VARCHAR(30) NOT NULL,
    SSN VARCHAR(10) PRIMARY KEY,
    SUPERSSN VARCHAR(10),
    SALARY DECIMAL(10,2) NOT NULL,
    DNUM INT,
    BDATE DATE,
    ADDRESS VARCHAR(50),
    SEX CHAR(1),
    FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUM)
);

CREATE TABLE PROJECT (
    PNAME VARCHAR(30) NOT NULL,
    PNUM INT PRIMARY KEY,
    PLOC VARCHAR(30),
    DNUM INT,
    FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUM)
);

CREATE TABLE WORKS_ON (
    ESSN VARCHAR(10),
    PNUM INT,
    HOURS DECIMAL(5,2),
    FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN),
    FOREIGN KEY (PNUM) REFERENCES PROJECT(PNUM)
);

INSERT INTO DEPARTMENT(DNAME,DNUM,MGR_SSN,MGR_START_DATE) VALUES
('ACCOUNTING',10,'E101','2020-01-01'),
('RESEARCH',20,'E102','2019-03-15'),
('SALES',30,'E103','2021-06-10');

INSERT INTO EMPLOYEE(FNAME,LNAME,SSN,SUPERSSN,SALARY,DNUM,BDATE,ADDRESS,SEX) VALUES
('ANMOL','THAPLIYAL','E101',NULL,40000,10,'2002-05-14','DEHRADUN','M'),
('RAHUL','MANKANI','E102','E101',35000,20,'2001-06-22','AJMER','M'),
('KAPIL','NEGI','E103','E102',45000,20,'1999-11-02','HARIDWAR','M'),
('SNIGDH','RAWAL','E104','E101',30000,30,'2003-02-17','LUCKNOW','M'),
('AUGUSTYA','THAKUR','E105','E102',50000,20,'2000-09-19','DELHI','M');

INSERT INTO PROJECT(PNAME,PNUM,PLOC,DNUM) VALUES
('Database System',1,'NEW YORK',10),
('AI Research',2,'DALLAS',20),
('Sales Analysis',3,'CHICAGO',30);

INSERT INTO WORKS_ON(ESSN,PNUM,HOURS) VALUES
('E101',1,10.0),
('E102',1,15.0),
('E103',1,12.0),
('E103',2,20.0),
('E104',3,18.0),
('E105',2,25.0),
('E105',1,10.0);

-- Q1
CREATE VIEW DEPT_MANAGER_VIEW AS
SELECT D.DNAME AS DEPT_NAME,
CONCAT(E.FNAME,' ',E.LNAME) AS MANAGER_NAME,
E.SALARY AS MANAGER_SALARY
FROM DEPARTMENT D
JOIN EMPLOYEE E ON D.MGR_SSN=E.SSN;

SELECT * FROM DEPT_MANAGER_VIEW;

-- Q2
CREATE VIEW EMP_SUPERVISOR_VIEW AS
SELECT CONCAT(E.FNAME,' ',E.LNAME) AS EMPLOYEE_NAME,
CONCAT(S.FNAME,' ',S.LNAME) AS SUPERVISOR_NAME,
E.SALARY AS EMPLOYEE_SALARY
FROM EMPLOYEE E
JOIN EMPLOYEE S ON E.SUPERSSN=S.SSN
JOIN DEPARTMENT D ON E.DNUM=D.DNUM
WHERE D.DNAME='RESEARCH';

SELECT * FROM EMP_SUPERVISOR_VIEW;

-- Q3
CREATE VIEW PROJECT_INFO_VIEW AS
SELECT P.PNAME AS PROJECT_NAME,
D.DNAME AS CONTROLLING_DEPT,
COUNT(DISTINCT W.ESSN) AS NUM_EMPLOYEES,
SUM(W.HOURS) AS TOTAL_HOURS
FROM PROJECT P
JOIN DEPARTMENT D ON P.DNUM=D.DNUM
JOIN WORKS_ON W ON P.PNUM=W.PNUM
GROUP BY P.PNAME,D.DNAME;

SELECT * FROM PROJECT_INFO_VIEW;

-- Q4
CREATE VIEW PROJECT_INFO_VIEW2 AS
SELECT P.PNAME AS PROJECT_NAME,
D.DNAME AS CONTROLLING_DEPT,
COUNT(DISTINCT W.ESSN) AS NUM_EMPLOYEES,
SUM(W.HOURS) AS TOTAL_HOURS
FROM PROJECT P
JOIN DEPARTMENT D ON P.DNUM=D.DNUM
JOIN WORKS_ON W ON P.PNUM=W.PNUM
GROUP BY P.PNAME,D.DNAME
HAVING COUNT(DISTINCT W.ESSN)>1;

SELECT * FROM PROJECT_INFO_VIEW2;