DROP DATABASE IF EXISTS COMPANY;
CREATE DATABASE COMPANY;
USE COMPANY;

CREATE TABLE EMPLOYEES (
EMPLOYEE_ID VARCHAR(10) PRIMARY KEY,
FIRST_NAME VARCHAR(17) NOT NULL,
LAST_NAME VARCHAR(17) NOT NULL,
DOB DATE,
SALARY DECIMAL(10,2) NOT NULL,
DEPARTMENT_ID VARCHAR(10)
);

INSERT INTO EMPLOYEES(EMPLOYEE_ID,FIRST_NAME,LAST_NAME,DOB,SALARY,DEPARTMENT_ID) VALUES
('E101','ANMOL','THAPLIYAL','2005-09-03',40000,'10'),
('E102','RAHUL','MANKANI','2005-09-08',35000,'20'),
('E103','KAPIL','NEGI','2006-09-15',45000,'20'),
('E104','SNIGDH','RAWAL','2005-06-12',30000,'30'),
('E105','AUGUSTYA','THAKUR','2005-08-16',50000,'20');

SELECT * FROM EMPLOYEES;

-- Q1
CREATE INDEX EMPLOYEE_IDX
ON EMPLOYEES(LAST_NAME,DEPARTMENT_ID);
SHOW INDEX FROM EMPLOYEES;

-- Q2
CREATE UNIQUE INDEX EMP_UNIQUE
ON EMPLOYEES(EMPLOYEE_ID);
SHOW INDEX FROM EMPLOYEES;

-- Q3
ALTER TABLE EMPLOYEES
ADD COLUMN REV_ID VARCHAR(10) GENERATED ALWAYS AS (REVERSE(EMPLOYEE_ID)) STORED;
CREATE INDEX EMP_REVERSE
ON EMPLOYEES(REV_ID);
SHOW INDEX FROM EMPLOYEES;

-- Q4
CREATE UNIQUE INDEX EMP_COMPOSITE
ON EMPLOYEES(EMPLOYEE_ID,DEPARTMENT_ID);

SELECT EMPLOYEE_ID,DEPARTMENT_ID,COUNT(*)
FROM EMPLOYEES
GROUP BY EMPLOYEE_ID,DEPARTMENT_ID
HAVING COUNT(*)>1;

-- Q5
CREATE INDEX EMP_UPPER
ON EMPLOYEES((UPPER(LAST_NAME)));
SELECT * FROM EMPLOYEES
WHERE UPPER(LAST_NAME)='THAKUR';

-- Q6
DROP INDEX EMP_UPPER ON EMPLOYEES;
SHOW INDEX FROM EMPLOYEES;
